services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
            target: development
        environment:
            APP_ENV: "dev"
            APP_SECRET: "1761987e3a9d1929d3b87bfa804d8fc3"
        volumes:
            - ./:/var/www/html:delegate
        ports:
            - 80:80